game:
  mode: classic
  round_time: 20
  start_time: 2019-11-30 15:30:00
  timezone: Europe/Moscow

  default_score: 0
  flag_lifetime: 5
  game_hardness: 10.0
  inflation: true

tasks:
  - checker: exoplanet/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: exoplanet
    places: 1
    puts: 2

tasks:
  - checker: grox/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: grox
    places: 1
    puts: 2

tasks:
  - checker: ice-and-fire/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: ice-and-fire
    places: 1
    puts: 2

tasks:
  - checker: martian/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: martian
    places: 1
    puts: 2

tasks:
  - checker: msp/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: msp
    places: 1
    puts: 2

tasks:
  - checker: planetzor/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: planetzor
    places: 1
    puts: 2  

tasks:
  - checker: spacesos/checker.py
    checker_timeout: 10
    checker_type: pfr
    gets: 2
    name: spacesos
    places: 1
    puts: 2  

teams:
  - ip: 10.10.10.2
    name: "SIGAN"

  - ip: 10.10.10.3
    name: "mbl"

  - ip: 10.10.10.4
    name: "freeplay_club"
  
  - ip: 10.10.10.5
    name: "n0-flag strat"

  
